name: Cclass request
title: "[Cclass Request:] Cclass = "
description: Request a new Cclass for the Open-CMSIS-Pack taxonomy. 
labels: [new Cclass]

body:
  - type: markdown
    attributes:
      value: >-
        Before requesting a new `Cclass` here, make sure that it is not covered by an existing `Cclass` in the file
        [`Open-CMSIS-Pack-Taxonomy.yaml`](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Taxonomy/blob/main/Open-CMSIS-Pack-Taxonomy.yaml).
        If this doesn't look right, raise a general [issue](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Taxonomy/issues/new).

  - type: input
    attributes:
      label: Cclass Name
      description: >-
        A Component Class (`Cclass`) is the top-level grouping of software components in the Open-CMSIS-Pack system.       
      placeholder: 'Example: MyStack'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Cclass Description
      description: >-
        Describe the purpose and scope of the `Cclass`.
      placeholder: 'Example: Implements a customer software stack for robotics using AI technology'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Cclass Mode
      description: >-
        The following **Mode** types allow validation tools to perform checks:
        
        - **Open:** vendors can add additional Cgroup names for their needs. There might be a check for duplicates in other packs.
        
        - **Device:** device specific software components. There is a check for a device condition as the components are device specific.
        
        - **Board:** board specific software components. There is a check for a board condition as the components are boards specific.
        
        - **Controlled:** extensions to the Cclass are possible but controlled by owner (=vendor). CMSIS, LVGL, or Memfault could be examples for such a Cclass.
        
        - **Bundle:** publish a complete software stack with fixed functionality (i.e. File System, TCP/IP stack, etc.). New vendors can add new bundle names for equivalent functionality.
        
        - **API:** for controlled API header files at CGroup level. Implementations using Csub can be provided by various vendors.
      options:
        - Open
        - Device
        - Board
        - Controlled
        - Bundle
        - API
    validations:
      required: true

  - type: input
    attributes:
      label: Cclass Owner
      description: |
        The company or organization requesting and maintaining the Cclass.
      placeholder: 'Example: My-Company-Name'
    validations:
      required: true

  - type: input
    attributes:
      label: Website
      description: >-
        For additional information about the software components you can add a relevant link.
        You can put "None" if you don't think there's a website.
      placeholder: 'https://www.open-cmsis-pack.org/'
    validations:
      required: false

  - type: input
    attributes:
      label: Contact
      description: >-
        For contacting you by email you may enter your email address or an support address for your software components. 
        If you put "None", we contact you using this GitHub issue.
      placeholder: 'myGroup@My-Company-Name.com'
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Additional Comments
      description: |
        Is there anything else we should know about the new Cclass? 
      placeholder: 'Example: The request for this Cclass is to enusre that MyStack can be used with other software packs from vendor ...'
    validations:
      required: false
