name: Cclass request
description: Request a new Cclass for the Open-CMSIS-Pack taxonomy. 
labels: [new Cclass]

body:
  - type: markdown
    attributes:
      value: >-
        #Issue: Cclass request

        A Component Class (`Cclass`) is the top-level grouping of software components in the Open-CMSIS-Pack system.
        Request a new [`Cclass`](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/cp_PackTutorial.html#cp_TutorialComponents)
        for the [Open-CMSIS-Pack taxonomy](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Taxonomy). 
        If this doesn't look right, [choose a different type]<todo: link>.

        Before requesting a new `Cclass` new issue, make sure that it is not covered by an existing `Cclass` in the file
        [`Open-CMSIS-Pack-Taxonomy.yaml`](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Taxonomy/blob/main/Open-CMSIS-Pack-Taxonomy.yaml).

  - type: input
    attributes:
      label: Cclass Name
      description: >-
        A Component Class (`Cclass`) is the top-level grouping of software components in the Open-CMSIS-Pack system.       
      placeholder: 'Example: MyStack'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Cclass Description
      description: >-
        Describe the purpose and scope of the `Cclass`.
      placeholder: 'Example: Implements a customer software stack for robotics using AI technology'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Cclass Mode
      description: >-
        The following **Mode** types allows validation tools to perform checks:

        - **Mode: Open** is used to allow extensions provided by multiple vendors. Every vendor can add additional Cgroup names. As a component has also a Cvendor, an name clash between different vendors can be resolved. Still it is recommended to avoid name clashes at the Cgroup level.
        
        - **Mode: Device** is used to define device specific software components. New Cgroup names are allowed, but each component must have a dependency to a device (otherwise similar to Mode: Open).
        
        - **Mode: Board** is used to define board specific software components. New Cgroup names are allowed, but each component must have a dependency to a board (otherwise similar to Mode: Open).
        
        - **Mode: Controlled** is used to describe that extensions to the Cclass are possible, but controlled by the Open-CMSIS-Pack working group or by the Owner (=vendor). CMSIS, LVGL, or Memfault could be examples for such a Cclass.
        
        - **Mode: Bundle** is used to publish a complete software stack with fixed functionality (i.e. File System, TCP/IP stack, etc.). Additional Cgroup names can only be added using the same Cvendor name. It is possible to have multiple bundles that use the same Cclass name.
        
        - **Mode: API** is used to publish unified API header files. Implementations can be provided by various vendors using a Csub name in the element. Depending on the attribute exclusive one or more implementations may be provided. This mode is triggered by the element <apis> of a software pack.
      options:
        - Open
        - Device
        - Board
        - Controlled
        - Bundle
        - API
    validations:
      required: true

  - type: input
    attributes:
      label: Cclass Owner
      description: |
        The company or organization requesting and maintaining the Cclass.
      placeholder: 'Example: My-Company-Name'
    validations:
      required: true

  - type: input
    attributes:
      label: Website
      description: >-
        For additional information about the software components you can add a relevant link.
        You can put "None" if you don't think there's a website.
      placeholder: 'https://www.open-cmsis-pack.org/'
    validations:
      required: false

  - type: input
    attributes:
      label: Contact
      description: >-
        For contacting you by email you may enter your email address or an support address for your software components. 
        If you put "None", we contact you using this GitHub issue.
      placeholder: 'myGroup@My-Company-Name.com'
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Additional Comments
      description: |
        Is there anything else we should know about the new Cclass? 
      placeholder: 'Example: The request for this Cclass is to enusre that MyStack can be used with other software packs from vendor ...'
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ** NOTE: Fields marked with an asterisk (*) are required. **
